# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrentLocation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrentLocation

    pod "SnapKit", '5.7.1'

end
